### ISSUE TITLE
Témabejelentő beállítása

### ISSUE THREAD

**Issue by KDawid** [mcserep/elteikthesis#1]
Kedves Máté!

Tudnál pár mondatot írni arról, hogyan kell a témabejelentőt megfelelően beállítani? Odáig eljutottam, hogy a \declarationplaceholder felelős ezért a szövegrészért, de nem mozgok elég otthonosan a tex világában.

**Comment by mcserep** [comment]
Azon nagyon nincsen mit beállítani, ugyanis oda a témabejelentő eredeti példányát kell beköttetni. Régebben ez papír alapon ment, 2019 ősz óta Neptun kérvény útján kerül leadásra, amiből a generált témabejelentő letölthető, és azt kell bekötni a 2. oldalnak.

**Comment by KDawid** [comment]
Köszönöm!
