### ISSUE TITLE
Mi az ősosztály?

### ISSUE THREAD

**Issue by kelna** [mcserep/elteikthesis#10]
Helló! LyX-ben próbálom importálni és szerkeszteni a sablont, de nem megy, mert az elteikthesis.cls egy egyedi osztály, amihez nem ismer layoutot a LyX. Ezt írják:
_"Find the basis class for your new class. Lets assume, the LaTeX class amcsiggraph.cls is a descendant of article.cls, then the lyx layout to use is article.layout."_

Tehát definiálnom kellene egyet, és elvileg ehhez elég annyi, hogy megmondom, miből származik az egyedi osztály. Erre utaló sort viszont nem találok az elteikhesis.cls fájlban. Miből származik? Vagy teljesen egyedi?

**Comment by mcserep** [comment]
Report
```latex
\LoadClass[a4paper, 12pt, oneside]{report}
```
