### ISSUE TITLE
Adding multiple external supervisors

### ISSUE THREAD

**Issue by ntvuong** [mcserep/elteikthesis#11]
Hello. Thank you so much for this template. 

Basically if I want to add multiple external supervisors to my thesis, 2 external supervisors to be exact, then how should this template be modified?

Thank you so much

**Comment by mcserep** [comment]
Hi @ntvuong ,

To add a second external supervisor to the cover page, you have to modify the template in the following way:

1. Add new commands for setting the name and the affiliation for the second external supervisor in a similar way it is done for the first external supervisor:
https://github.com/mcserep/elteikthesis/blob/d54fc84c7bc5f1cfa0c217edf979add2095d0c7b/elteikthesis.cls#L82-L83

2. Modify the cover page accordingly here (e.g. place the second supervisor under the first one):
https://github.com/mcserep/elteikthesis/blob/d54fc84c7bc5f1cfa0c217edf979add2095d0c7b/elteikthesis.cls#L500-L512

**Comment by ntvuong** [comment]
Thank you so much for your reply. I modified it successfully.
