### ISSUE TITLE
Az Irodalomjegyzéket nem szúrja be

### ISSUE THREAD

**Issue by Zadam01** [mcserep/elteikthesis#17]
Jó napot! Leszedtem a sémát, és minden módosítás nélkül szeretném lefuttatni TexShopban. A tartalomjegyzékbe berakja az irodalomjegyzéket, jó helyen is van, de magába a dokumentumba már nem helyezi bele, mint új oldal. A logok között meg találtam egy ilyet:

(/usr/local/texlive/2023/texmf-dist/tex/latex/listings/lstlang1.sty) [13])
[14] (./samples_hu/sum.tex
4. fejezet.
) [15] (./samples_hu/sim.tex [16]
A. f\"uggel\'ek.
) [17] [18]

LaTeX Warning: Empty bibliography on input line 83.

(./elteikthesis_hu.lof) [19] (./elteikthesis_hu.lot) [20]
(./elteikthesis_hu.loa) [21] (./elteikthesis_hu.lol) [22]
(./elteikthesis_hu.aux)

LaTeX Warning: There were undefined references.

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

Package biblatex Warning: Please (re)run BibTeX on the file(s):
(biblatex)                elteikthesis_hu
(biblatex)                and rerun LaTeX afterwards.

 )
(see the transcript file for additional information)`

Amikor saját projektet szeretnék létrehozni, az irodalomjegyzék ott sem kerül beszúrásra.

Esetleg tudna nekem segíteni ebben a problémában?

**Comment by Zadam01** [comment]
Köszönöm, a problémám megoldódott. A bibtex parancsot kellett nálam alkalmazni a biber parancs helyett.

**Comment by mcserep** [comment]
Helló @Zadam01!

A sablon `biber` használatára van konfigurálva, azaz a `biblatex` csomag a `backend=biber` opcióval ban betöltve. Ha `bibtex`-et futtattál, akkor szerintem az *Irodalomjegyzék* a kimeneti PDF-ben nem lesz helyes.
