### ISSUE TITLE
Update the text, Acknowledgements and Acknowledgments are different things

### ISSUE THREAD

**Issue by CodeTyperPro** [mcserep/elteikthesis#19]
It was intended to mean Acknowledgments instead of Acknowledgements. Please fix the text!
Cambridge Dictionary definitions:

- **Acknowledgement**: a letter or email to say that you have received something that someone sent to you.
- **Acknowledgments**: something given to thank someone for what they have done.

https://dictionary.cambridge.org/dictionary/english/acknowledgment?q=Acknowledgment
https://dictionary.cambridge.org/dictionary/english/acknowledgement?q=Acknowledgement

Check:
https://github.com/mcserep/elteikthesis/blob/2fea114971a363208197d5e3d52d3a41e7958120/elteikthesis.cls#L146

Thank you!

**Comment by mcserep** [comment]
Hi @CodeTyperPro,

Both forms are correct and mean the same to my knowledge. Acknowledg**e**ment is mostly used in British English, while Acknowledgment (without the e) is the American English form.

Both words are used to express gratitude and appreciation. In the template, the British English version is used.
In the Cambridge Dictionary [you linked](https://dictionary.cambridge.org/dictionary/english/acknowledgment?q=Acknowledgment), see:
![image](https://github.com/mcserep/elteikthesis/assets/7405458/e64ad987-3a81-4aaf-816a-923dff4c0e26)

Feel free to change it of course in your own thesis, if you would like.
