### ISSUE TITLE
Use `pdfusetitle`

### ISSUE THREAD

**Issue by jtotht** [mcserep/elteikthesis#3]
I used `\documentclass[...,pdfusetitle]{elteikthesis}` in my thesis, and I think it’s worth including in the theme or at least in the .tex template. It causes the output PDF to have its title set to the the thesis title, which is a nice feature—instead of a bunch of `thesis.pdf`s, each has a descriptive title that appears on the browser tab, in the standalone PDF reader etc. What do you think?

**Comment by mcserep** [comment]
Good point, added in d36f02d.
