### ISSUE TITLE
How to implement end page List of Equations

### ISSUE THREAD

**Issue by Purefekt** [mcserep/elteikthesis#7]
Hi, great project. Can you share how can i implement List of equations at the end like List of codes or tables. The equations start and end this way

\begin{equation}
    ..........
\end{equation}

**Comment by mcserep** [comment]
Hello,
To my knowledge it requires some workaround to implement, you may find some possible solutions here:
https://tex.stackexchange.com/questions/173102/table-of-equations-like-list-of-figures

**Comment by Purefekt** [comment]
Hi, Thanks it worked
