### ISSUE TITLE
Table of Content link does not take you to the correct page

### ISSUE THREAD

**Issue by Purefekt** [mcserep/elteikthesis#8]
Hi, for the List of figures, tables etc, on clicking the link in the toc, it only takes you to the Bibliography.

Thanks

**Comment by mcserep** [comment]
Hello,
It was already fixed in fa5281d00ff6b63102c1fddc3d1f6f2f8d8e788d, just a new release has not been made since yet. Are you using the newest state on the master branch?

**Comment by Purefekt** [comment]
I have been using the template i found on overleaf's website. I think ill try to make these changes in my current work since i made a lot of changes to the template and im extremely novice at Tex so i don't think i will be able to repeat those changes 😅

**Comment by mcserep** [comment]
The change is simple and straightforward (just add some `\phantomsection` to the thesis.tex), it should be easy to apply based on the referenced commit.

**Comment by Purefekt** [comment]
It worked, thanks a lot!
