### ISSUE TITLE
Please reply asap, thesis deadline!

### ISSUE THREAD

**Issue by Purefekt** [mcserep/elteikthesis#9]
Hi, i had a internal and an external advisor. Can you please tell me how to change the template to add the external supervisor under the internal supervisor? I am attaching the code for the title page.

% ------------------------------
% Internal title
\renewcommand{\maketitle}{
	\begin{titlepage}

		\begin{center}

			\begin{tabular}{ c c }
				\multirow{4}{*}{\hspace{-1.0cm}\includegraphics[width=0.25\textwidth]{\logofilename}}

				& {\sc \Large \makecell{\univname}} \vspace{0.3cm}\\
				& {\sc \Large \makecell{\facname}} \vspace{0.5cm}\\
				& {\sc \large \makecell{\deptname}}
			\end{tabular}

			\vspace{5.0cm}
			{\bf \LARGE \thesistitle}
			\vspace{4.0cm}

			\ifdefined\extsupaff
				{\it \large \authorlabel:}\\
				{\large \authorname}\\
				\degreename\\
				\vspace{2.0cm}

				\begin{tabular}{ l c l }
					{\it \large \intsuplabel:} &
					\hspace{4.0cm} &
					{\it \large \extsuplabel:}\\

					{\large \supname} &
					\hspace{4.0cm} &
					{\large \extsupname}\\

					\supaff &
					\hspace{4.0cm} &
					\extsupaff\\
				\end{tabular}
			\else
				\vspace{1.0cm}
				\begin{tabular}{ l c l }
					{\it \large \suplabel:} &
					\hspace{4.0cm} &
					{\it \large \authorlabel:}\\

					{\large \supname} &
					\hspace{4.0cm} &
					{\large \authorname}\\

					\supaff &
					\hspace{4.0cm} &
					\degreename\\
				\end{tabular}
			\fi

			\vfill

			\cityname\\
			\thesisyear\\

		\end{center}

	\end{titlepage}
}
% ------------------------------

Thanks!

**Comment by mcserep** [comment]
Unfortunately I did not have time to answer this and only got back here now. Hope you managed to solve it and submit your thesis.

**Comment by Purefekt** [comment]
Hello, it worked out before the submission :)
